/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.myplugin.clients.opennms.v1.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FilterDef
 */
public class FilterDef {
  @SerializedName("name")
  private String name = null;

  @SerializedName("parameters")
  private List<FilterParamDef> parameters = null;

  public FilterDef name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilterDef parameters(List<FilterParamDef> parameters) {
    this.parameters = parameters;
    return this;
  }

  public FilterDef addParametersItem(FilterParamDef parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<FilterParamDef>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  public List<FilterParamDef> getParameters() {
    return parameters;
  }

  public void setParameters(List<FilterParamDef> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterDef filterDef = (FilterDef) o;
    return Objects.equals(this.name, filterDef.name) &&
        Objects.equals(this.parameters, filterDef.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterDef {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
