/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.myplugin.clients.opennms.v1.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * FilterMetaData
 */
public class FilterMetaData {
  @SerializedName("canonicalName")
  private String canonicalName = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("backend")
  private String backend = null;

  @SerializedName("parameters")
  private List<FilterParamMetaData> parameters = null;

  public FilterMetaData canonicalName(String canonicalName) {
    this.canonicalName = canonicalName;
    return this;
  }

   /**
   * Get canonicalName
   * @return canonicalName
  **/
  public String getCanonicalName() {
    return canonicalName;
  }

  public void setCanonicalName(String canonicalName) {
    this.canonicalName = canonicalName;
  }

  public FilterMetaData name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public FilterMetaData description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public FilterMetaData backend(String backend) {
    this.backend = backend;
    return this;
  }

   /**
   * Get backend
   * @return backend
  **/
  public String getBackend() {
    return backend;
  }

  public void setBackend(String backend) {
    this.backend = backend;
  }

  public FilterMetaData parameters(List<FilterParamMetaData> parameters) {
    this.parameters = parameters;
    return this;
  }

  public FilterMetaData addParametersItem(FilterParamMetaData parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<FilterParamMetaData>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  public List<FilterParamMetaData> getParameters() {
    return parameters;
  }

  public void setParameters(List<FilterParamMetaData> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FilterMetaData filterMetaData = (FilterMetaData) o;
    return Objects.equals(this.canonicalName, filterMetaData.canonicalName) &&
        Objects.equals(this.name, filterMetaData.name) &&
        Objects.equals(this.description, filterMetaData.description) &&
        Objects.equals(this.backend, filterMetaData.backend) &&
        Objects.equals(this.parameters, filterMetaData.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canonicalName, name, description, backend, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FilterMetaData {\n");
    
    sb.append("    canonicalName: ").append(toIndentedString(canonicalName)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    backend: ").append(toIndentedString(backend)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
