/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.myplugin.clients.opennms.v1.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.util.Date;
import java.util.Objects;
/**
 * OnmsAcknowledgment
 */
public class OnmsAcknowledgment {
  @SerializedName("id")
  private Integer id = null;

  @SerializedName("log")
  private String log = null;

  /**
   * Gets or Sets ackType
   */
  @JsonAdapter(AckTypeEnum.Adapter.class)
  public enum AckTypeEnum {
    @SerializedName("Unspecified")
    UNSPECIFIED("Unspecified"),
    @SerializedName("Alarm")
    ALARM("Alarm"),
    @SerializedName("Notification")
    NOTIFICATION("Notification");

    private String value;

    AckTypeEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AckTypeEnum fromValue(String input) {
      for (AckTypeEnum b : AckTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AckTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AckTypeEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AckTypeEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AckTypeEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("ackType")
  private AckTypeEnum ackType = null;

  /**
   * Gets or Sets ackAction
   */
  @JsonAdapter(AckActionEnum.Adapter.class)
  public enum AckActionEnum {
    @SerializedName("Unspecified")
    UNSPECIFIED("Unspecified"),
    @SerializedName("Acknowledge")
    ACKNOWLEDGE("Acknowledge"),
    @SerializedName("Unacknowledge")
    UNACKNOWLEDGE("Unacknowledge"),
    @SerializedName("Escalate")
    ESCALATE("Escalate"),
    @SerializedName("Clear")
    CLEAR("Clear");

    private String value;

    AckActionEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static AckActionEnum fromValue(String input) {
      for (AckActionEnum b : AckActionEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<AckActionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AckActionEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public AckActionEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return AckActionEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("ackAction")
  private AckActionEnum ackAction = null;

  @SerializedName("ackUser")
  private String ackUser = null;

  @SerializedName("ackTime")
  private Date ackTime = null;

  @SerializedName("refId")
  private Integer refId = null;

  public OnmsAcknowledgment id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

  public OnmsAcknowledgment log(String log) {
    this.log = log;
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  public String getLog() {
    return log;
  }

  public void setLog(String log) {
    this.log = log;
  }

  public OnmsAcknowledgment ackType(AckTypeEnum ackType) {
    this.ackType = ackType;
    return this;
  }

   /**
   * Get ackType
   * @return ackType
  **/
  public AckTypeEnum getAckType() {
    return ackType;
  }

  public void setAckType(AckTypeEnum ackType) {
    this.ackType = ackType;
  }

  public OnmsAcknowledgment ackAction(AckActionEnum ackAction) {
    this.ackAction = ackAction;
    return this;
  }

   /**
   * Get ackAction
   * @return ackAction
  **/
  public AckActionEnum getAckAction() {
    return ackAction;
  }

  public void setAckAction(AckActionEnum ackAction) {
    this.ackAction = ackAction;
  }

  public OnmsAcknowledgment ackUser(String ackUser) {
    this.ackUser = ackUser;
    return this;
  }

   /**
   * Get ackUser
   * @return ackUser
  **/
  public String getAckUser() {
    return ackUser;
  }

  public void setAckUser(String ackUser) {
    this.ackUser = ackUser;
  }

  public OnmsAcknowledgment ackTime(Date ackTime) {
    this.ackTime = ackTime;
    return this;
  }

   /**
   * Get ackTime
   * @return ackTime
  **/
  public Date getAckTime() {
    return ackTime;
  }

  public void setAckTime(Date ackTime) {
    this.ackTime = ackTime;
  }

  public OnmsAcknowledgment refId(Integer refId) {
    this.refId = refId;
    return this;
  }

   /**
   * Get refId
   * @return refId
  **/
  public Integer getRefId() {
    return refId;
  }

  public void setRefId(Integer refId) {
    this.refId = refId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnmsAcknowledgment onmsAcknowledgment = (OnmsAcknowledgment) o;
    return Objects.equals(this.id, onmsAcknowledgment.id) &&
        Objects.equals(this.log, onmsAcknowledgment.log) &&
        Objects.equals(this.ackType, onmsAcknowledgment.ackType) &&
        Objects.equals(this.ackAction, onmsAcknowledgment.ackAction) &&
        Objects.equals(this.ackUser, onmsAcknowledgment.ackUser) &&
        Objects.equals(this.ackTime, onmsAcknowledgment.ackTime) &&
        Objects.equals(this.refId, onmsAcknowledgment.refId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, log, ackType, ackAction, ackUser, ackTime, refId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnmsAcknowledgment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    ackType: ").append(toIndentedString(ackType)).append("\n");
    sb.append("    ackAction: ").append(toIndentedString(ackAction)).append("\n");
    sb.append("    ackUser: ").append(toIndentedString(ackUser)).append("\n");
    sb.append("    ackTime: ").append(toIndentedString(ackTime)).append("\n");
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
