/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.myplugin.clients.opennms.v1.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;
/**
 * OnmsAcknowledgmentCollection
 */

public class OnmsAcknowledgmentCollection {
  @SerializedName("objects")
  private List<OnmsAcknowledgment> objects = null;

  @SerializedName("offset")
  private Integer offset = null;

  @SerializedName("count")
  private Integer count = null;

  @SerializedName("totalCount")
  private Integer totalCount = null;

  public OnmsAcknowledgmentCollection objects(List<OnmsAcknowledgment> objects) {
    this.objects = objects;
    return this;
  }

  public OnmsAcknowledgmentCollection addObjectsItem(OnmsAcknowledgment objectsItem) {
    if (this.objects == null) {
      this.objects = new ArrayList<OnmsAcknowledgment>();
    }
    this.objects.add(objectsItem);
    return this;
  }

   /**
   * Get objects
   * @return objects
  **/
  public List<OnmsAcknowledgment> getObjects() {
    return objects;
  }

  public void setObjects(List<OnmsAcknowledgment> objects) {
    this.objects = objects;
  }

  public OnmsAcknowledgmentCollection offset(Integer offset) {
    this.offset = offset;
    return this;
  }

   /**
   * Get offset
   * @return offset
  **/
  public Integer getOffset() {
    return offset;
  }

  public void setOffset(Integer offset) {
    this.offset = offset;
  }

  public OnmsAcknowledgmentCollection count(Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count
  **/
  public Integer getCount() {
    return count;
  }

  public void setCount(Integer count) {
    this.count = count;
  }

  public OnmsAcknowledgmentCollection totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * Get totalCount
   * @return totalCount
  **/
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnmsAcknowledgmentCollection onmsAcknowledgmentCollection = (OnmsAcknowledgmentCollection) o;
    return Objects.equals(this.objects, onmsAcknowledgmentCollection.objects) &&
        Objects.equals(this.offset, onmsAcknowledgmentCollection.offset) &&
        Objects.equals(this.count, onmsAcknowledgmentCollection.count) &&
        Objects.equals(this.totalCount, onmsAcknowledgmentCollection.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objects, offset, count, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnmsAcknowledgmentCollection {\n");
    
    sb.append("    objects: ").append(toIndentedString(objects)).append("\n");
    sb.append("    offset: ").append(toIndentedString(offset)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
