/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.opennms.client.impl.model;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonValue;

import java.util.Date;
import java.util.Objects;
/**
 * OnmsAcknowledgment
 */
public class OnmsAcknowledgment {
  @JsonProperty("id")
  private Integer id = null;

  /**
   * Gets or Sets ackType
   */
  public enum AckTypeEnum {
    @JsonProperty("UNSPECIFIED")
    UNSPECIFIED("UNSPECIFIED"),
    @JsonProperty("ALARM")
    ALARM("ALARM"),
    @JsonProperty("NOTIFICATION")
    NOTIFICATION("NOTIFICATION");

    private String value;

    AckTypeEnum(String value) {
      this.value = value;
    }

    @JsonValue
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static AckTypeEnum fromValue(String input) {
      for (AckTypeEnum b : AckTypeEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
  }

  @JsonProperty("ackType")
  private AckTypeEnum ackType = null;

  /**
   * Gets or Sets ackAction
   */

  public enum AckActionEnum {
      @JsonProperty("UNSPECIFIED")
      UNSPECIFIED("UNSPECIFIED"),
      @JsonProperty("ACKNOWLEDGE")
      ACKNOWLEDGE("ACKNOWLEDGE"),
      @JsonProperty("UNACKNOWLEDGE")
      UNACKNOWLEDGE("UNACKNOWLEDGE"),
      @JsonProperty("ESCALATE")
      ESCALATE("ESCALATE"),
      @JsonProperty("CLEAR")
      CLEAR("CLEAR");

      private String value;

      AckActionEnum(String value) {
          this.value = value;
      }

      @JsonValue
      public String getValue() {
          return value;
      }

      @Override
      public String toString() {
          return String.valueOf(value);
      }
  }

  @JsonCreator
  public static AckActionEnum fromValue(String input) {
  for (AckActionEnum b : AckActionEnum.values()) {
    if (b.value.equals(input)) {
      return b;
    }
  }
  return null;
}

  @JsonProperty("ackAction")
  private AckActionEnum ackAction = null;

  @JsonProperty("ackUser")
  private String ackUser = null;

  @JsonProperty("ackTime")
  private Date ackTime = null;

  @JsonProperty("refId")
  private Integer refId = null;

  public OnmsAcknowledgment id(Integer id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  public Integer getId() {
    return id;
  }

  public void setId(Integer id) {
    this.id = id;
  }

   /**
   * Get log
   * @return log
  **/

  public OnmsAcknowledgment ackType(AckTypeEnum ackType) {
    this.ackType = ackType;
    return this;
  }

   /**
   * Get ackType
   * @return ackType
  **/
  public AckTypeEnum getAckType() {
    return ackType;
  }

  public void setAckType(AckTypeEnum ackType) {
    this.ackType = ackType;
  }

  public OnmsAcknowledgment ackAction(AckActionEnum ackAction) {
    this.ackAction = ackAction;
    return this;
  }

   /**
   * Get ackAction
   * @return ackAction
  **/
  public AckActionEnum getAckAction() {
    return ackAction;
  }

  public void setAckAction(AckActionEnum ackAction) {
    this.ackAction = ackAction;
  }

  public OnmsAcknowledgment ackUser(String ackUser) {
    this.ackUser = ackUser;
    return this;
  }

   /**
   * Get ackUser
   * @return ackUser
  **/
  public String getAckUser() {
    return ackUser;
  }

  public void setAckUser(String ackUser) {
    this.ackUser = ackUser;
  }

  public OnmsAcknowledgment ackTime(Date ackTime) {
    this.ackTime = ackTime;
    return this;
  }

   /**
   * Get ackTime
   * @return ackTime
  **/
  public Date getAckTime() {
    return ackTime;
  }

  public void setAckTime(Date ackTime) {
    this.ackTime = ackTime;
  }

  public OnmsAcknowledgment refId(Integer refId) {
    this.refId = refId;
    return this;
  }

   /**
   * Get refId
   * @return refId
  **/
  public Integer getRefId() {
    return refId;
  }

  public void setRefId(Integer refId) {
    this.refId = refId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    OnmsAcknowledgment onmsAcknowledgment = (OnmsAcknowledgment) o;
    return Objects.equals(this.id, onmsAcknowledgment.id) &&
        Objects.equals(this.ackType, onmsAcknowledgment.ackType) &&
        Objects.equals(this.ackAction, onmsAcknowledgment.ackAction) &&
        Objects.equals(this.ackUser, onmsAcknowledgment.ackUser) &&
        Objects.equals(this.ackTime, onmsAcknowledgment.ackTime) &&
        Objects.equals(this.refId, onmsAcknowledgment.refId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, ackType, ackAction, ackUser, ackTime, refId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class OnmsAcknowledgment {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    ackType: ").append(toIndentedString(ackType)).append("\n");
    sb.append("    ackAction: ").append(toIndentedString(ackAction)).append("\n");
    sb.append("    ackUser: ").append(toIndentedString(ackUser)).append("\n");
    sb.append("    ackTime: ").append(toIndentedString(ackTime)).append("\n");
    sb.append("    refId: ").append(toIndentedString(refId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
