/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.opennms.client.impl.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * QueryMetadata
 */

public class QueryMetadata {
  @SerializedName("resources")
  private List<QueryResource> resources = null;

  @SerializedName("nodes")
  private List<QueryNode> nodes = null;

  public QueryMetadata resources(List<QueryResource> resources) {
    this.resources = resources;
    return this;
  }

  public QueryMetadata addResourcesItem(QueryResource resourcesItem) {
    if (this.resources == null) {
      this.resources = new ArrayList<QueryResource>();
    }
    this.resources.add(resourcesItem);
    return this;
  }

   /**
   * Get resources
   * @return resources
  **/
  public List<QueryResource> getResources() {
    return resources;
  }

  public void setResources(List<QueryResource> resources) {
    this.resources = resources;
  }

  public QueryMetadata nodes(List<QueryNode> nodes) {
    this.nodes = nodes;
    return this;
  }

  public QueryMetadata addNodesItem(QueryNode nodesItem) {
    if (this.nodes == null) {
      this.nodes = new ArrayList<QueryNode>();
    }
    this.nodes.add(nodesItem);
    return this;
  }

   /**
   * Get nodes
   * @return nodes
  **/
  public List<QueryNode> getNodes() {
    return nodes;
  }

  public void setNodes(List<QueryNode> nodes) {
    this.nodes = nodes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    QueryMetadata queryMetadata = (QueryMetadata) o;
    return Objects.equals(this.resources, queryMetadata.resources) &&
        Objects.equals(this.nodes, queryMetadata.nodes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(resources, nodes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class QueryMetadata {\n");
    
    sb.append("    resources: ").append(toIndentedString(resources)).append("\n");
    sb.append("    nodes: ").append(toIndentedString(nodes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
