/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.opennms.client.impl.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * WrappedPrimitive
 */
public class WrappedPrimitive {
  @SerializedName("list")
  private List<Double> list = null;

  public WrappedPrimitive list(List<Double> list) {
    this.list = list;
    return this;
  }

  public WrappedPrimitive addListItem(Double listItem) {
    if (this.list == null) {
      this.list = new ArrayList<Double>();
    }
    this.list.add(listItem);
    return this;
  }

   /**
   * Get list
   * @return list
  **/
  public List<Double> getList() {
    return list;
  }

  public void setList(List<Double> list) {
    this.list = list;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WrappedPrimitive wrappedPrimitive = (WrappedPrimitive) o;
    return Objects.equals(this.list, wrappedPrimitive.list);
  }

  @Override
  public int hashCode() {
    return Objects.hash(list);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrappedPrimitive {\n");
    
    sb.append("    list: ").append(toIndentedString(list)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
