/*
 * OpenNMS V1 RESTful API
 * OpenNMS V1 RESTful API
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package it.arsinfo.opennms.client.impl.api;


import it.arsinfo.opennms.client.impl.handler.ApiClient;
import it.arsinfo.opennms.client.impl.handler.ApiException;
import it.arsinfo.opennms.client.impl.model.OnmsAcknowledgmentCollection;

import java.io.IOException;

public class DefaultApi {
    private ApiClient apiClient;

    public DefaultApi(ApiClient apiClient) {
        this.apiClient = apiClient;
    }

    public OnmsAcknowledgmentCollection getAcks() throws ApiException {
        String relativePath="/acks";
        return apiClient.get(relativePath, OnmsAcknowledgmentCollection.class);
    }

}
